POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "name": "Linda Martinez",
    "address": "707 Oak St, Countryside, MI",
    "email": "lindamartinez@example.com",
    "phoneNumber": "555-789-0123"
}

###

GET http://localhost:8080/user HTTP/1.1

###

GET http://localhost:8080/user/2 HTTP/1.1

###

PATCH http://localhost:8080/user/2 HTTP/1.1

{
    "name": "Sample-Test",
    "email": "test@gmail.com"
}

###

DELETE http://localhost:8080/user/10 HTTP/1.1
