POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "name": "Sample",
    "address": "Test Street",
    "email": "test@gmail.com",
    "phoneNumber": "081234567890"
}

###

GET http://localhost:8080/users HTTP/1.1

###

GET http://localhost:8080/users/3 HTTP/1.1

###

PATCH http://localhost:8080/users/2 HTTP/1.1

{
    "name": "Sample-Updated",
    "email": "Test@gmail.com"
}

###

DELETE http://localhost:8080/users/3 HTTP/1.1
