POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "name": "Sample",
    "address": "Test Street",
    "email": "test@gmail.com",
    "phoneNumber": "081234567890"
}

###

GET http://localhost:8080/user HTTP/1.1

###

GET http://localhost:8080/user/2 HTTP/1.1

###

PATCH http://localhost:8080/user/2 HTTP/1.1

{
    "name": "Sample-Test",
    "email": "test@gmail.com"
}

###

DELETE http://localhost:8080/user/7 HTTP/1.1
